#include <stdio.h> 
#include <wchar.h>  // wide char handling
#include "Hello.h"	// generated by javah

JNIEXPORT void JNICALL Java_Hello_sayHi (JNIEnv *env, jobject obj, jstring who, jint times) { 
	jint i; 
	jboolean iscopy; 
	const char *name; 
	name = (*env)->GetStringUTFChars(env, who, &iscopy); 
	for (i = 0; i < times; i++) {
		printf("Hello %s\n", name);
	}
}


JNIEXPORT void JNICALL Java_Hello_stringSanitize(JNIEnv *env, jobject obj, jstring str){

	jboolean iscopy; 
	wchar_t *str_ptr;
	str_ptr = (*env)->GetStringCritical(env, str, &iscopy); 
	str_ptr[0] = '*';
	str_ptr[1] = '*';
	str_ptr[2] = '*';
	str_ptr[3] = '*';
	wprintf(L"[native] was the buffer a copy? : %ls\n", iscopy ? L"true" : L"false");
	wprintf(L"[native] %ls\n", str_ptr);
}