#include <stdio.h> 
#include <wchar.h>  // wide char handling
#include "Log.h"	// generated by javah



JNIEXPORT void JNICALL Java_Log_Log(JNIEnv *env, jobject obj, jstring str){
	jboolean iscopy; 
	wchar_t *str_ptr;
	str_ptr = (*env)->GetStringCritical(env, str, &iscopy); 
	wprintf(L"[Log] %ls\n", str_ptr);
}
JNIEXPORT void JNICALL Java_Log_LogPassword(JNIEnv *env, jobject obj, jstring str){

	jboolean iscopy; 
	wchar_t *str_ptr;
	str_ptr = (*env)->GetStringCritical(env, str, &iscopy); 
	str_ptr[0] = '*';
	str_ptr[1] = '*';
	str_ptr[2] = '*';
	str_ptr[3] = '*';
	wprintf(L"[Log] was the buffer a copy? : %ls\n", iscopy ? L"true" : L"false");
	wprintf(L"[Log] %ls\n", str_ptr);
}